### ISSUE TITLE
Configuration mode with button

### ISSUE THREAD

**Issue by jharmn** [enc-X/sonoff-homie#1]
Obviously $reset can be used, if the sonoff is connected to a valid MQTT host.

In the event that invalid configuration is written, or if the wifi password changes, the device will be not be configurable. 
I was thinking maybe a long press on the button would trigger the configuration mode. 

Thoughts?

P.S. I'm really thankful you wrote this...looks like you took care of quite a few things I didn't have to ;)

**Comment by piotrC4** [comment]
It's already done:
`  Homie.setResetTrigger(PIN_BUTTON, LOW, 10000);
`
You only have to press button more then 10seconds.

**Comment by jharmn** [comment]
Ah damn didn't see that, well done :) 
I'll have to hold the button longer. Seems like a valuable one to throw in the README.
Thanks!
